name: Octostache wrapper Action
description: A Github action to replicate the octopus variable substitution feature

branding:
  icon: hash
  color: purple
  
inputs:
  variables-file:
    description: An optional yaml file containing variables to use in the substitution.
    required: false
  files-with-substitutions:
    description: 'A comma separated list of files with #{variables} that need substitution.'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Run the octostash project
      shell: pwsh
      run: |
        if ($IsWindows) { 
          $executablePath = "${{ github.action_path }}/.build-win/OctostacheCmd.exe" 
        } 
        else { 
          $executablePath = "${{ github.action_path }}/.build-linux/OctostacheCmd" 
          chmod 777 $executablePath
        }

        if ("${{ inputs.variables-file }}") {
          Invoke-Expression "$executablePath --files-with-substitutions `"${{ inputs.files-with-substitutions }}`" --variables-file `"${{ inputs.variables-file }}`""
        }
        else {
          Invoke-Expression "$executablePath --files-with-substitutions `"${{ inputs.files-with-substitutions }}`""
        }
