name: 'Octostache wrapper Action'
description: 'A Github action to replicate the octopus variable substitution feature'
branding:
  icon: hash
  color: purple
inputs:
  variables-file:
    description: |
      The json file that holds the variables and values to be used in the substitution.
      Defined as JSON object, e.g. {"Variable1":"value1","Variable2":"value2"}
    required: true
  file-with-substitutions:
    description: 'The file that has substitutions to be performed.'
    required: true
  output-file:
    description: 'The file the substitution results should be saved to.  Generally the same value as file-with-substitutions.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.variables-file }}
    - ${{ inputs.file-with-substitutions }}
    - ${{ inputs.output-file }}
