name: Octostache wrapper Action
description: A Github action to replicate the octopus variable substitution feature.  Change to the source code.

branding:
  icon: hash
  color: purple
  
inputs:
  variables-file:
    description: An optional yaml file containing variables to use in the substitution.
    required: false
  files-with-substitutions:
    description: 'A comma separated list of files with #{variables} that need substitution.'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Run the octostash project
      shell: pwsh
      run: |
        $executablePath = if ($IsWindows) { "${{ github.action_path }}/.build-win/OctostacheCmd.exe" } else { "${{ github.action_path }}/.build-linux/OctostacheCmd" }

        if (!$IsWindows) {
          chmod 777 $executablePath
        }

        if ("${{ inputs.variables-file }}") {
          Invoke-Expression "$executablePath --variables-file `"${{ inputs.variables-file }}`" --files-with-substitutions `"${{ inputs.files-with-substitutions }}`""
        }
        else {
          Invoke-Expression "$executablePath --files-with-substitutions `"${{ inputs.files-with-substitutions }}`""
        }
        echo "Test out a source code change"
